---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      name: pod-adminer
      labels:
        type: web
    spec:
      containers:
        - name: myadminer
          image: adminer
