apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: web1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: key1
                operator: In
                values:
                  - value1
  containers:
    - name: nginx
      image: nginx

