# 01-new-httpd-podantiaffinity.yml
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-httpd-new
  labels:
    type: web
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: type
                operator: In
                values:
                  - web
          topologyKey: kubernetes.io/hostname
  containers:
    - name: myhttpd-new
      image: httpd

