apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 1  # Set the desired number of replicas as per your requirement
  selector:
    matchLabels:
      app: httpd  # Replace 'app' label with your desired label
  template:
    metadata:
      labels:
        app: httpd  # Replace 'app' label with your desired label
    spec:
      containers:
        - name: myhttpd
          image: httpd

