apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    name: mynginx
spec:
  containers:
  - name: mynginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        hostPort: 8082