---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    type: pv
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt
...
#++++++++++++++++++++++++++++++++++++++++++++++++++
# Break Down above defintion file #
# ++++++++++++++++++++++++++++++++++++++++++++++++++++
# apiVersion -->specifies the Kubernetes API version for the resource.
# kind -->indicates the type of resource, which is PersistentVolume in this case.
# metadata -->contains metadata about the PersistentVolume, such as the name and labels.
# spec -->defines the specifications for the PersistentVolume.
# storageClassName -->specifies the storage class name for the PersistentVolume.
# capacity --> defines the capacity of the PersistentVolume, which is set to 10Gi (10 gigabytes) in this example.
# accessModes -->specifies the access modes for the PersistentVolume. Here, it's set to ReadWriteOnce, meaning it can be mounted as read-write by a single node.
# hostPath -->defines the host path on the underlying node where the data will be stored. In this case, it's set to /mnt/data. Please ensure that the path exists on the node where the PersistentVolume will be used.
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# [ec2-user@Eks-server ~]$ kubectl get pv
# NAME        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
# pv-volume   10Gi       RWO            Retain           Available           manual                  7s
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

