---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    type: web
spec:
  containers:
    - name: myhttpd
      image: httpd
      volumeMounts:
        - name: tcs-volume
          mountPath: /usr/local/apache2/htdocs/
  volumes:
    - name: tcs-volume
      persistentVolumeClaim:
        claimName: task-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: svc-httpd
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 9090
      nodePort: 30005
  selector:
    type: web

