---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    type: pv
    author: thej
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
  labels:
    type: pvc
    author: thej
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-nginx
  labels:
    type: web
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      name: pod-nginx
      labels:
        type: web
    spec:
      containers:
        - name: mywebserver
          image: nginx
          volumeMounts:
            - name: new-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: new-volume
          persistentVolumeClaim:
            claimName: pvc-volume 
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  labels:
    type: nginx-svc
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30005
  selector:
    type: web
...
