---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: mysql-pod
      labels:
        type: db
    spec:
      containers:
        - name: mydb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: thej
          volumeMounts:
            - name: wipro-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: wipro-volume
          persistentVolumeClaim:
            claimName: pvc-volume


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    type: db
spec:
  clusterIP: None
  ports:
    - name: tcp
      port: 3306
      protocol: TCP
  selector:
    app: mysql
---
