---
apiVersion: v1
kind: Pod
metadata:
  name: pod-postgres
spec:
  containers:
    - name: postgresdb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
