---
apiVersion: v1
kind: Pod
metadata:
  name: pod-postgres
  labels:
    type: db
spec:
  containers:
    - name: mydatabase
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-postgres
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-postgres
              key: username
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: secret-postgres
              key: dbname 
           
