---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: pod-nginx
      labels:
        app: backend
    spec:
      containers:
        - name: mynginx
          image: nginx
