---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30009
  selector:
    type: proxy
    author: thej
...
