---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-03
  labels:
    type: proxy-deployment
    author: thej
spec:
  replicas: 2
  selector:
    matchLabels:
      type: proxy
      author: thej
  template:
    metadata:
      name: my-nginx-template
      labels:
        type: proxy
        author: thej
    spec:
      containers:
        - name: mynginx-pod
          image: nginx

