---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    type: webserver
    author: thej
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webhttpd
      author: thej
  template:
    metadata:
      name: pod-httpd
      labels:
        type: webhttpd
        author: thej
    spec:
      containers:
        - name: myhttp
          image: httpd
...
