---
apiVersion: v1
kind: Service
metadata:
  name: service-httpd
spec:
  type: NodePort
  ports:
    - targetPort: 80  
      port: 80        
      nodePort: 30009 
  selector:
    type: webhttpd
    author: thej

