apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-pod
  template:
    metadata:
      labels:
        app: ubuntu-pod
    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu:latest
          command: ["sleep", "infinity"]
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m


...
## ---------examples------------------------------------------------------ 
#
#The Deployment creates a single replica of the pod.
#The matchLabels field specifies the label selector to match the pod with the deployment.
#The pod template includes a container named ubuntu-container.
#The ubuntu:latest image is used, which pulls the latest version of the Ubuntu image from Docker Hub.
#The container's command is set to ["sleep", "infinity"], which keeps the container running indefinitely.
#You can save this YAML code in a file (e.g., ubuntu-deployment.yaml) and apply it to your Kubernetes cluster using the kubectl apply command:
#resoucrces means that ubuntu system soud only consume that minimum cpu is 200 memory and maximum shoud take 500 memory 
