---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-pod
  template:
    metadata:
      labels:
        app: ubuntu-pod
    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu:latest
          command: ["sleep", "infinity"]
...

