# file 11-taint-nginx-Deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-taint-nginx
  labels:
    type: distraction
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web1
      author: thej
  template:
    metadata:
      name: pod-nginx
      labels:
        type: web1
        author: thej
    spec:
      containers:
        - name: mynginx
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: slave2
                  operator: In
                  values:
                    - thej2
...
#above content is related to nginx webserver it should need service port to access from browser
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: web1
    author: thej
...
# above service file content it should linked with help of selctors section both selectors type=web1 and author=thej should be match then only it will and we can able to access from browser
# ============this file related tainted concept so above nginx pod should not place on slave2 machine ==========================
# ==============they still showing pending only=================================================
#

