# file 12-tolerance-nginx.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    type: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
      author: thej
  template:
    metadata:
      name: pod-nginx
      labels:
        type: webserver
        author: thej
    spec:
      containers:
        - name: mynginx
          image: nginx
      tolerations:
        - key: slave2
          operator: Equal
          value: thej2
          effect: NoSchedule

...
# above image is nginx so we need ports to access from browser 
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: webserver
    author: thej
...
