# file 16-Namespace.yml
---
apiVersion: v1
kind: Namespace
metadata:
  name: wipro-ns
...
# above file is a namespace  wipro-ns
# its same like one vpc namespace inside kuberenetes cluster
# below creating pod httpd inside wipro-ns
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-httpd
  namespace: wipro-ns
  labels:
    type: web
    author: thej
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web
      author: thej
  template:
    metadata:
      name: pod-httpd
      labels:
        type: web
        author: thej
    spec:
      containers:
        - name: myweb
          image: httpd
...

# above file container httpd image that is webserver we need to access from browser for that we need to create service file NodePort or LoadBalancer 
---
apiVersion: v1
kind: Service
metadata:
  name: service-httpd-wipro
  namespace: wipro-ns
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    type: web
    author: thej
...
# from above file service definition file for nodeport to httpd service in customised namespace wipro-ns 
#  kubectl get all -n wipro-ns ==== this is the commad to see resources 
