# 17-mysql-deployment-wordpress-service-wordpress.yml 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: pod-mysql
      labels:
        type: db
    spec:
      containers:
        - name: mydatabase
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_USER
              value: thej
            - name: MYSQL_DB
              value: mydb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    type: web
    author: thej
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web
      author: thej
  template:
    metadata:
      name: pod-wordpress
      labels:
        type: web
        author: thej
    spec:
      containers:
        - name: mywordpress
          image: wordpress

---
apiVersion: v1
kind: Service
metadata:
  name: service-wordpress
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    type: web
    author: thej


