# 18-mysql-deployment-adminer-service-adminer.yml 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: pod-mysql
      labels:
        type: db
    spec:
      containers:
        - name: mydatabase
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypassword
            - name: MYSQL_DATABASE
              value: mydatabase
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_PASSWORD
              value: mypassword

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  labels:
    type: web
    author: thej
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web
      author: thej
  template:
    metadata:
      name: pod-adminer
      labels:
        type: web
        author: thej
    spec:
      containers:
        - name: newadminer
          image: adminer

---
apiVersion: v1
kind: Service
metadata:
  name: service-adminer
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30009
  selector:
    type: web
    author: thej


