#  21-postgres-adminre-from-chatgpt.yml 
#  this is taken from chatgpt  
---

# postgres-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_DB
          value: mydatabase

---

# phpmyadmin-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin-pod
  labels:
    app: phpmyadmin
spec:
  containers:
    - name: phpmyadmin
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - containerPort: 80
          hostPort: 8080
      env:
        - name: PMA_HOST
          value: postgres-pod   # Use the hostname of the PostgreSQL pod

