# file 22-postgres-pgadmin-chatgpt.yml
# this is taken from chatgpt 
---
# postgres-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_DB
          value: mydatabase

---

# pgadmin-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: pgadmin-pod
  labels:
    app: pgadmin
spec:
  containers:
    - name: pgadmin
      image: dpage/pgadmin4:latest
      ports:
        - containerPort: 80
          hostPort: 8080
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@example.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
        - name: PGADMIN_LISTEN_PORT
          value: "80"
        - name: PGADMIN_DEFAULT_SERVER
          value: postgres-pod   # Use the hostname of the PostgreSQL pod

