# postgres-pod.yaml
#  file name 23-postgres-adminer-podService-nodeport.yml


apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_DB
          value: mydatabase

---

# adminer-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: adminer-pod
  labels:
    app: adminer
spec:
  containers:
    - name: adminer
      image: adminer
---

# adminer-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008

