# 24-tolerance-machine-mysql-and-adminer-in-different-machine.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
  labels:
    type: db
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: pod-mysql
      labels:
        type: db
    spec:
      containers:
        - name: mydb
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypassword
            - name: MYSQL_DATABASE
              value: mydatabase
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_PASSWORD
              value: mypassword
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                 - key: slave2
                   operator: In
                     values:
                       - thej-node2
      


