# To add mysql multiple pods only in tainted machine 
# By default when you run mysql pods or any pod it might be place wgere ever slave we dont know 
# but in here i want to place perticular like mysql pods only will be place in perticular slave only and remaining pods will not be placed on that for that we do implement some steps for that  
# MySQL run on only tainted machine in that case we need to some steps 
# step1: attach affinity on slave in the cluster like command # kubectl label nodes slave-id key=value
# step2: create a definition file add affinity section to place pods on that slave
# step3: run definition file 
# step4: observe pods in the cluster Now automatically mysql two pods will be running on only o that slave based affinity section 
# step5: apply taint on the same slave now no other pods will not placed on that machine  Now our mysql pods will be separated 
# step6: to apply taint on machine in the cluster ## kubectl taint slave-id key=value:NoSchedule ## (provide same key and value) 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymnt-mysql
  labels:
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: pod-mysql
      labels:
        type: db
    spec:
      containers:
        - name: mydb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypassword
            - name: MYSQL_DATABASE
              value: mydatabase
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_PASSWORD
              value: mypassword

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: key1
                  operator: In
                  values:
                    - value1


...
