---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-pod
  template:
    metadata:
      labels:
        app: ubuntu-pod
    spec:
      containers:
        - name: thej-ubuntu
          image: ubuntu:latest
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: newvolume
              mountPath: /data
      volumes:
        - name: newvolume
          emptyDir: {}

        

...

