---
apiVersion: v1
kind: Pod
metadata:
  name: pod-ngix
  labels:
    type: proxy
spec:
  containers:
    - name: nginx-image
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: myvolume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: myvolume
      emptyDir: {}
...
#==============================================================================#
# above image is nginx creating pod out of image 
# here creating  volume as myvolume  even if container craches that inside container volume mountpath not loss 
#
# The Pod also defines a volume named "myvolume" and mounts it at the path "/usr/share/nginx/html" inside the container.
# The volume is of type "emptyDir", which means it is created when the Pod is scheduled to a node and exists as long as the Pod is running. An emptyDir volume is initially empty but can be used to share data between containers within the same Pod.
#
# here empty dir volume data will be available when pod recreted after crashes 
# but softwares are not available we need to install manually
# to overcome this we need to create a customised docker image then use here to available desired softwares inside
# =====================================================================================#
