---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    type: proxy
    author: thej
spec:
  replicas: 2
  selector:
    matchLabels:
      type: proxy
      author: thej
  template:
    metadata:
      name: pod-nginx
      labels:
        type: proxy
        author: thej
    spec:
      containers:
        - name: mynginx
          image: nginx
          volumeMounts:
            - name: thej-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: thej-volume
          emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 8080
  selector:
    type: proxy
    author: thej
...
     
#============================================================================#
# here from above nginx image creating pod from image 
#
