---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rc-httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      name: pod-httpd
      labels:
        type: web
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8081
